<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="4.0.0.2" ID="f7cf6b68-5c7a-4ab2-9e14-0b7eedb8ff22" Name="Sintegrates">
	<Dependencies>
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
		<SchemePartition ID="d1b372f3-7565-4309-9037-5e5a0969d94e" Name="Standard solution" />
	</Dependencies>
	<Description>Для тестирования</Description>
	<SchemeTable ID="47107d7a-3a8c-47f0-b800-2a45da222ff4" Name="KrDocState" IsExternal="true" />
	<SchemeTable ID="1f4018b2-4c44-4741-8c64-dafd9937881d" Name="SiAccesssettings" IsExternal="true" />
	<SchemeTable ID="e403c897-59fb-4473-a06f-3672784aca58" Name="SiDoctypesroute" IsExternal="true" />
	<SchemeTable ID="5ae0b298-2717-43b9-8c07-be000e32f58a" Name="SiInfo" IsExternal="true" />
	<SchemeTable ID="cb5a8def-176d-417c-9000-ddec14ac5982" Name="SiRouteOrder" IsExternal="true" />
</SchemePartition>