<?xml version="1.0" encoding="utf-8"?>
<SchemePartition SchemeVersion="2.6.15.0" ID="9c77e8fa-4271-478a-9893-054c0a0b3cca" Name="Sintegrates">
	<Dependencies>
		<SchemePartition ID="29f90c69-c1ef-4cbf-b9d5-7fc91cd68c67" Name="Default" />
		<SchemePartition ID="d1b372f3-7565-4309-9037-5e5a0969d94e" Name="Standard solution" />
	</Dependencies>
	<Description>Для тестирования</Description>
	<SchemeTable ID="eb29db76-443b-4635-aac1-ef434a0ad9ba" Name="DocumentTypes" IsExternal="true" />
	<SchemeTable ID="47107d7a-3a8c-47f0-b800-2a45da222ff4" Name="KrDocState" IsExternal="true" />
	<SchemeTable ID="11753225-5fca-44b7-b090-b651ec8d83ab" Name="SiAccesssettings" IsExternal="true" />
	<SchemeTable ID="969d3b78-66a1-4e87-8e45-c59c363b19ae" Name="SiDoctypesroute" IsExternal="true" />
	<SchemeTable ID="6c95567f-f85d-43fb-8568-025c575f9b6a" Name="SiInfo" IsExternal="true" />
	<SchemeTable ID="9cc82497-3f7e-43c9-b430-114726b5579f" Name="SiRouteOrder" IsExternal="true" />
</SchemePartition>